### ISSUE TITLE
[Preview 6] Blazor (Server Side) overriding identity via scaffolding throws error

### ISSUE THREAD

**Issue by muheebhussain** [aspnet/AspNetCore#11179]
[Preview 6] Blazor Server Side overriding identity via scaffolding throws an error.

<details>
<summary>
<strong>dotnet 3.0.100-preview6-012264</strong> <br>

1. Upgrade to .net core 3.0.100-preview6-012264
2. Create a new asp.net core web application project, select server side blazor. 
3. Change Identity to individual user account

After project creation right click Areas/Identity folder, Add New Scaffold Item, Override all files throws error.
![image](https://user-images.githubusercontent.com/14001175/59434418-e7487200-8dc1-11e9-8281-ad4ca431bf4d.png)
</summary>
</details>

**Comment by mihaimyh** [comment]
Microsoft.VisualStudio.Web.CodeGeneration.Design nuget package must be updated to 3.0.0-preview6 also.

**Comment by sidebarpronto** [comment]
This error occurs when the page layout field is left blank. You can get around it by creating a dummy layout page and using that as your layout file. But the bigger problem is once the scaffolding templates are generated your Blazor project wont run. I created #11228.

**Comment by danroth27** [comment]
This specific error should now be fixed with the latest preview version of Visual Studio.

**Comment by muheebhussain** [comment]
@danroth27 Still not able be overriding identity with scaffolding

![image](https://user-images.githubusercontent.com/14001175/63657515-6589a300-c779-11e9-8c57-996f8d485b48.png)

**Comment by Gpd1969** [comment]
I have this same issue. I've updated to the latest Version of Visual Studio Preview and Core framework as well.

net core 3.0.100-preview8
Microsoft Visual Studio Community 2019 Preview
Version 16.3.0 Preview 2.0
VisualStudio.16.Preview/16.3.0-pre.2.0+29209.152
