### ISSUE TITLE
UseMvc helper text misspells "UseEndpointRouting" as "UseEndpointRounting"

### ISSUE THREAD

**Issue by Malivil** [aspnet/AspNetCore#11467]
### Describe the bug
MVC API project which calls UseMvc method shows helper text with "MvcOptions.EnableEndpointRou**n**ting" that is misspelled and should be "MvcOptions.EnableEndpointRouting" instead. Note the extra "n" in the original message.

### To Reproduce
1. Using this version of ASP.NET Core '3.0.100-preview6-012264'
2. Create a MVC API project (or upgrade an existing project from .Net Core 2.2)
3. Call IApplicationBuilder::UseMvc within the Startup::Configure method
4. Mouse over the UseMvc call to view the helper text which mentioned setting the MvcOptions.EnableEndpointRounting option.
5. Note that "MvcOptions.EnableEndpointRou**n**ting" is misspelled and should be "MvcOptions.EnableEndpointRouting" instead

### Expected behavior
"MvcOptions.EnableEndpointRou**n**ting" is misspelled and should be "MvcOptions.EnableEndpointRouting" instead

### Screenshots
Image: https://i.imgur.com/axqQ90w.png

### Additional context
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-012264
 Commit:    be3f0c1a03

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\

Host (useful for support):
  Version: 3.0.0-preview6-27804-01
  Commit:  fdf81c6faf

.NET Core SDKs installed:
  1.1.7 [C:\Program Files\dotnet\sdk]
  1.1.13 [C:\Program Files\dotnet\sdk]
  2.1.100 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.2.204 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  3.0.100-preview6-012264 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Malivil.
This is already fixed and will be part of preview7 release.

**Comment by flcdrg** [comment]
Using preview 8 and this typo is still present - https://github.com/aspnet/AspNetCore/blob/master/src/Analyzers/Analyzers/src/StartupAnalyzer.Diagnostics.cs#L40

**Comment by adrianwright109** [comment]
Looks like the fix was done under PR #13209 but was committed to the master branch so that's why its not showing up in any of the preview releases.

**Comment by flcdrg** [comment]
I'm not sure what the process is to request a commit be merged to the 3.0 branch
