### ISSUE TITLE
Failed to start platform. Reason: [object ProgressEvent]

### ISSUE THREAD

**Issue by GerritBergen** [aspnet/AspNetCore#12045]
### Describe the bug
Often times when I start my client side blazor app the browser console throws `Failed to start platform. Reason: [object ProgressEvent]` and the app never loads. Just stays on the splash screen.

### To Reproduce
I wish I could confidently reproduce this but it just happens sometimes, and a few browser refreshes makes it work again.

### Screenshots
![image](https://user-images.githubusercontent.com/29714139/60971887-1c79ae80-a2f3-11e9-834e-44a4cd5f3984.png)

### Additional context
Using FireFox 69.0b3

.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview6-012264
 Commit:    be3f0c1a03

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\

Host (useful for support):
  Version: 3.0.0-preview6-27804-01
  Commit:  fdf81c6faf

.NET Core SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
  3.0.100-preview6-012264 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @GerritBergen.
It would help, if you could provide some more details and/or logs, if you have any.

**Comment by mkArtakMSFT** [comment]
Also, do you see any failed requests in the Network tab?

**Comment by GerritBergen** [comment]
Running in Edge Dev gives a bit more info. Most of the dll files are returning 304.
As of this run, Mono.WebAssembly.Interop.Dll & Microsoft.AspNetCore.Components.Browser.Dll shows (cancelled) in the status column. But that's just the weird thing, this changes with each refresh. Sometimes they all come in. Other times more/different ones show cancelled.

![Annotation 2019-07-10 124511](https://user-images.githubusercontent.com/29714139/60987955-ab48f400-a310-11e9-80f5-4c363c4e7493.png)

I'm sure I've got something setup wrong somewhere. I forgot to mention in the original post that I am running using Kestral if that helps.

**Comment by GerritBergen** [comment]
Probably useless information because it's minified JS, but this is where the error occurs in blazor.webassembly.js:
![Annotation 2019-07-10 134556](https://user-images.githubusercontent.com/29714139/60991776-2dd5b180-a319-11e9-8407-c5f91187668f.png)

**Comment by mkArtakMSFT** [comment]
@SteveSandersonMS do you have any recommendations regarding this?

**Comment by SteveSandersonMS** [comment]
It definitely appears to be a problem with serving files to the browser, not a problem with any code running inside the browser. This is separate from Blazor I'm afraid.

You'll need to figure out why your server is unable to send static files to your browser.

**Comment by GerritBergen** [comment]
Do you have any suggestions as to what could cause that?

**Comment by SteveSandersonMS** [comment]
It could be that your web server is faulty or misconfigured in some way, your browser is faulty or misconfigured in some way, or that some other thing such as anti malware software is interfering. I’m afraid that’s all I can suggest.

**Comment by GerritBergen** [comment]
A bunch of debugging later, I found this error in my server console right when the browser fails.

> Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection ErrorException: HTTP/2 connection error (PROTOCOL_ERROR): Pseudo-header field found in request headers after regular header fields.

Not really sure what's going on, but **disabling Http2** made the issue go away for me.
Not ideal, but I think I'll stick with that for now.

Thanks for your help

**Comment by mkArtakMSFT** [comment]
@anurse FYI

**Comment by anurse** [comment]
Oof, that is a weird one. @GerritBergen would you be up for doing a little additional diagnostics here to see if we can track down the server issue? I'm glad disabling HTTP/2 worked for you but would like to figure out if we can track down the original issue.

Since you're using the Edge Dev version (I presume you mean the Chromium-based version?), there is a way to export raw networking data from that. These instructions would also work in Google Chrome (replace `edge://` with `chrome://`)

1. Open a new Edge window and navigate to `edge://net-export`.
1. I think you can leave the "Strip private information" option button checked. We may end up needing more detail (raw bytes) though and if that's the case, I'll check in with you on how to avoid unintentionally sharing private data.
1. Click "Start Logging to Disk"
1. Reproduce the scenario.
1. Click "Stop Logging"

Then attach the file by renaming it to end `.txt` and dragging-and-dropping it on to the GitHub comment box (don't paste the file as it will be very large!).

If you have concerns about sharing this publicly, feel free to email it to me at `[my github username]@microsoft.com`.

I'm going to re-open and move to `area-servers` to investigate there.

**Comment by GerritBergen** [comment]
@anurse Sure! I need a couple days as I'm swamped right now. I'll update this thread when I send the email :)

**Comment by GerritBergen** [comment]
@anurse Email has been sent.

**Comment by anurse** [comment]
@GerritBergen thanks for the email! I think I've been able to identify that this is a known HTTP/2 protocol corruption issue that we introduced in 3.0 and _should_ have resolved in preview 7. If you'd like to verify that, you can check out our CI nightly builds from https://github.com/dotnet/core-sdk#installers-and-binaries (The "master" column is currently versioned **preview 8** but the "release/3.0.1xx" column should have our "candidate" **preview 7** release) or you can wait for the official preview 7 release.

If you are still seeing this after preview 7, please let us know in a new issue!

**Comment by coryflucas** [comment]
@anurse I seem to have hit the same (or a similar issue), see #12190. My issue does not appear to be fixed in preview 7.  I tried the nightly docker image and I still receive the same exception.

**Comment by anurse** [comment]
@GerritBergen I'm going to close this now as I think we've got your scenario covered.

@coryflucas We'll cover your issue in the linked thread. It looks like your proxy (envoy) is corrupting the frames.

**Comment by GerritBergen** [comment]
@anurse I've just updated to Preview 7 and unfortunately the issue is still here, although the error in the console is different.

![Annotation 2019-07-29 104008](https://user-images.githubusercontent.com/29714139/62057269-54d32500-b1ed-11e9-94b7-3c5f40ac44f2.png)
![Annotation 2019-07-29 104034](https://user-images.githubusercontent.com/29714139/62057273-57357f00-b1ed-11e9-843d-eff7b806c0d5.png)

> info: Microsoft.AspNetCore.Server.Kestrel[31]
      Connection id "0HLOK69K7TU57": HPACK decoding error while decoding headers for stream ID 157.
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.HPack.HPackDecodingException: Index 86 is outside the bounds of the header field table.
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.HPack.DynamicTable.get_Item(Int32 index)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.HPack.HPackDecoder.GetHeader(Int32 index)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.HPack.HPackDecoder.GetHeader(Int32 index)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.HPack.HPackDecoder.OnIndexedHeaderField(Int32 index, IHttpHeadersHandler handler)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.HPack.HPackDecoder.OnByte(Byte b, IHttpHeadersHandler handler)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.HPack.HPackDecoder.Decode(ReadOnlySequence`1& data, Boolean endHeaders, IHttpHeadersHandler handler)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.DecodeHeadersAsync(Boolean endHeaders, ReadOnlySequence`1& payload)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessHeadersFrameAsync[TContext](IHttpApplication`1 application, ReadOnlySequence`1& payload)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessRequestsAsync[TContext](IHttpApplication`1 application)

**Comment by Tratcher** [comment]
> HPackDecodingException: Index 86 is outside the bounds of the header field table.

That's a new exception. It may still be related to the prior one that we're tracking in #12190, but I'm going to re-open this to ensure we track both.

**Comment by anurse** [comment]
Yep, sounds different. We're continuing HTTP/2 hardening through the final previews and GA so we'll keep investigating.

**Comment by anurse** [comment]
@GerritBergen can you capture a network trace of some kind? Wireshark would be nice (but you'll need to use unencrypted HTTP/2, and I'm not sure you can do that with Chrome), or you could use the 'net-export' stuff I referenced [above](https://github.com/aspnet/AspNetCore/issues/12045#issuecomment-510635052)

**Comment by Tratcher** [comment]
After investigating https://github.com/aspnet/AspNetCore/issues/12190#issuecomment-517029076 I've found that it could also lead to this IndexOutOfRangeException depending on how many times DynamicTable.Insert is called.

Closing as a duplicate.
