### ISSUE TITLE
Calling Request.EnableRewind throw on 3.0.0-preview7

### ISSUE THREAD

**Issue by bruno-garcia** [aspnet/AspNetCore#12505]
An ASP.NET Core 3 app calling out to a library which depends on `Microsoft.AspNetCore.Hosting 2.x` and access `HttpContext.Request.EnableRewind()` throws an exception.

### To Reproduce
I have a repro here: https://github.com/bruno-garcia/aspnetcore3-hosting2.x-enable-rewind-throws

1. .NET SDK `3.0.100-preview7-012821`.
1. Using this version of ASP.NET Core '3.0.0-preview7.19365.7 '
2. Create a new class library targeting `netstandard2.0`
3. Add dependency to `Microsoft.AspNetCore.Hosting` version 2.2
4. Call `HttpContext.Request.EnableRewind()` in it.
5. Use the library from the ASP.NET Core 3 app

### Expected behavior
Request buffering happens

### Error:
```
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLOG3BFKK5BS", Request id "0HLOG3BFKK5BS:00000001": An unhandled exception was thrown by the application.
System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.Internal.BufferingHelper' from assembly 'Microsoft.AspNetCore.Http, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Class1.<>c.<<EnableRewind>b__0_0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Class1.<>c.<EnableRewind>b__0_0(HttpContext context, Func`1 next)
   at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass0_1.<Use>b__1(HttpContext context)
   at Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Hosting.HostingApplication.ProcessRequestAsync(Context context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

```

Raised here: https://github.com/getsentry/sentry-dotnet/issues/249

In all fairness the extension method in question is under `Microsoft.AspNetCore.Http.Internal` and even on `2.1` it was also available `EnableBuffering`. I've replaced the two in the library and it's working properly.

**Comment by jkotalik** [comment]
@davidfowl is this a scenario we still try to support where we have different dependencies to ASP.NET Core?

**Comment by davidfowl** [comment]
This is part of the pubternal move to internal. We haven’t written the uber announcement for that as yet.

**Comment by WellspringCS** [comment]
Could be *ENTIRELY* unrelated, but I am trying to add one feature to preview 7 and found this thread because the error thrown looks similar. For what it's worth... I add one dependency as follows:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Cloud.Diagnostics.AspNetCore" Version="3.0.0-beta13"/>
  </ItemGroup>

</Project>
````
Then in Program.cs go this route (There is no support as yet for `CreateHostBuilder`)...
```
using Google.Cloud.Diagnostics.AspNetCore;
...

       public static IWebHostBuilder CreateWebHostBuilder(string[] args) {
            var webHostBuilder = WebHost.CreateDefaultBuilder(args)
                .UseGoogleDiagnostics("my-project", "my-service", "my-version")
                .UseStartup<Startup>();
            return webHostBuilder;
        }
```

Finally adjust Startup.cs as follows:


```
 public void ConfigureServices(IServiceCollection services)
        { 
            services.AddGoogleExceptionLogging(options =>
            {
                // Replace ProjectId with your Google Cloud Project ID.
                options.ProjectId = "my-project";
                // Replace Service with a name or identifier for the service.
                options.ServiceName = "my-service";
                // Replace Version with a version for the service.
                options.Version = "my-version";
            });

            services.AddControllers();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        { 
            // Use before handling any requests to ensure all unhandled exceptions are reported.
            app.UseGoogleExceptionLogging();
...
```

Error thrown:

```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/2 GET https://localhost:5333/  
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLOGD52FHONE", Request id "0HLOGD52FHONE:00000001": An unhandled exception was thrown by the application.
System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.Internal.DefaultHttpRequest' from assembly 'Microsoft.AspNetCore.Http, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Google.Cloud.Diagnostics.AspNetCore.Labels.FromHttpContext(HttpContext httpContext)
   at Google.Cloud.Diagnostics.AspNetCore.CloudTraceMiddleware.Invoke(HttpContext httpContext, TraceHeaderContext traceHeaderContext)
   at Google.Cloud.Diagnostics.AspNetCore.ErrorReportingExceptionLoggerMiddleware.Invoke(HttpContext httpContext)
   at Google.Cloud.Diagnostics.AspNetCore.ErrorReportingExceptionLoggerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
Microsoft.AspNetCore.Server.Kestrel: Error: Connection id "0HLOGD52FHONE", Request id "0HLOGD52FHONE:00000001": An unhandled exception was thrown by the application.
```

I could be talking out of turn and apologize if this is the wrong thread to share the above. I have opened [a related thread with Google](https://github.com/googleapis/google-cloud-dotnet/issues/3259) , but of course I'm wondering in light of the similarity if there might be an issue from the ASP.NET Core 3.0 side as well.

**Comment by Tratcher** [comment]
@WellspringCS  That's related only in that there's a dependency mismatch.

**Comment by WellspringCS** [comment]
OK, so likely to go away when they release an updated version, I take it.

**Comment by anurse** [comment]
Closing as this should be fixed when referencing the latest versions.

**Comment by sc1994** [comment]
This problem persists after version `3.0.100-preview8-013656` is specified, with the same error.
Do I need to do more?

**Comment by runxc1** [comment]
So reading this thread it isn't clear whether or not this is something that you can do in 3.0 as I am not seeing the method in preview 8.  If the method is being removed is there still a way to read the Request Body a second time in say a logging extension?

**Comment by runxc1** [comment]
@sc1994 if I read this correctly you would need to change any calls to EnableRewind to EnableBuffering as shown in the the pull request that sentry committed to fix this in their code. https://github.com/getsentry/sentry-dotnet/pull/250/commits/520bb783761040ce336925a8376ed1e7c0dd31c7
