### ISSUE TITLE
When exception occurs during Startup.Configure propagate to webhost 

### ISSUE THREAD

**Issue by arabelaa** [aspnet/AspNetCore#13157]
### Is your feature request related to a problem? Please describe.
In  `Configure(IApplicationBuilder app, IHostingEnvironment env)`  I am registering a method using `app.ApplicationServices` instance. This method throws an exception when i can't make a socket connection (in my case i tried to connect to AMQP client).

I noticed if I move the registration inside `ConfigureServices(IServiceCollection services)` the exception bubbles up to my webhost. To be able to to this inside `ConfigureServices` I had to get an instance of serviceProvider by using  `services.BuildServiceProvider()` (which I am not sure if it's a good idea). 

### Describe the solution you'd like
I was wondering if it is possible to propagate exceptions that occur during `Configure` stage to webhost.

**Comment by arabelaa** [comment]
@Tratcher This option doesn't help with the scenario mentioned by me. 

If you throw an exception inside `public void Configure(IApplicationBuilder app, IHostingEnvironment env)` this will not stop the webHost starting (regardless of the setting you mentioned above). And this is what I want to achieve with this feature request. 

I can have a look where in the pipeline Configure method is called and see how hard is to make the exception (when occurs, of course) propagate to webHost. 

But I was wondering if I am the only one seeing value in this feature request?

**Comment by Tratcher** [comment]
Where are you running the app? In IIS (in proc or out of proc)? Or in a console app using Kestrel directly?

Here's a simple repro showing an exception from Configure propagating to Main when using Kestrel in a console app. This is the default behavior, no configuration is required.
```
        public void Configure(IApplicationBuilder app)
        {
            app.Run((httpContext) =>
            {
                var payload = _helloWorldBytes;
                var response = httpContext.Response;

                response.StatusCode = 200;
                response.ContentType = "text/plain";
                response.ContentLength = payload.Length;

                return response.BodyWriter.WriteAsync(payload).GetAsTask();
            });

            throw new System.Exception("Startup Exception");
        }
```

```
Application startup exception: System.Exception: Startup Exception
   at PlaintextApp.Startup.Configure(IApplicationBuilder app) in D:\github\AspNetCore\src\Servers\Kestrel\samples\PlaintextApp\Startup.cs:line 34
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.MethodInfoExtensions.InvokeWithoutWrappingExceptions(MethodInfo methodInfo, Object obj, Object[] parameters) in D:\github\AspNetCore\src\Hosting\hosting\src\Internal\MethodInfoExtensions.cs:line 17
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder) in D:\github\AspNetCore\src\Hosting\hosting\src\Internal\ConfigureBuilder.cs:line 56
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder) in D:\github\AspNetCore\src\Hosting\hosting\src\Internal\ConfigureBuilder.cs:line 20
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app) in D:\github\AspNetCore\src\Hosting\hosting\src\Startup\ConventionBasedStartup.cs:line 25
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication() in D:\github\AspNetCore\src\Hosting\hosting\src\Internal\WebHost.cs:line 228
Unhandled exception. System.Exception: Startup Exception
   at PlaintextApp.Startup.Configure(IApplicationBuilder app) in D:\github\AspNetCore\src\Servers\Kestrel\samples\PlaintextApp\Startup.cs:line 34
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.MethodInfoExtensions.InvokeWithoutWrappingExceptions(MethodInfo methodInfo, Object obj, Object[] parameters) in D:\github\AspNetCore\src\Hosting\hosting\src\Internal\MethodInfoExtensions.cs:line 17
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder) in D:\github\AspNetCore\src\Hosting\hosting\src\Internal\ConfigureBuilder.cs:line 56
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder) in D:\github\AspNetCore\src\Hosting\hosting\src\Internal\ConfigureBuilder.cs:line 20
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app) in D:\github\AspNetCore\src\Hosting\hosting\src\Startup\ConventionBasedStartup.cs:line 25
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication() in D:\github\AspNetCore\src\Hosting\hosting\src\Internal\WebHost.cs:line 228
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken) in D:\github\AspNetCore\src\Hosting\hosting\src\Internal\WebHost.cs:line 148
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage) in D:\github\AspNetCore\src\Hosting\hosting\src\WebHostExtensions.cs:line 109
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage) in D:\github\AspNetCore\src\Hosting\hosting\src\WebHostExtensions.cs:line 147
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token) in D:\github\AspNetCore\src\Hosting\hosting\src\WebHostExtensions.cs:line 94
   at PlaintextApp.Startup.Main(String[] args) in D:\github\AspNetCore\src\Servers\Kestrel\samples\PlaintextApp\Startup.cs:line 48
   at PlaintextApp.Startup.<Main>(String[] args)

D:\github\AspNetCore\artifacts\bin\PlaintextApp\Debug\netcoreapp3.0\PlaintextApp.exe (process 12656) exited with code -532462766.
Press any key to close this window . . .
```

IIS out-of-proc has different behavior because the console is not usually visible. It captures the errors and shows an error page. See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/web-host?view=aspnetcore-2.2#detailed-errors

IIS in-proc is a bit different, and has changed significantly across versions. You're using 2.2, correct? @jkotalik what's in-proc's setting for CaptureStartupErrrors in 2.2?

**Comment by arabelaa** [comment]
After some digging I noticed that having (I am using Microsoft.ApplicationInsights.AspNetCore 2.7.0)

 ` services.AddApplicationInsightsTelemetry();` in `ConfigureServices` the exception is swallowed. 
If I remove the applicationInsights telemetry configuration the exception bubbles up. 
You can add that to your sample application, it is quite easy to reproduce.
Didn't expect that behavior. 

But you are right, the feature is already there.
The problem is in combination with application insights configuration.

**Comment by anurse** [comment]
Closing as it sounds like the issue has been resolved and there is no action needed in ASP.NET Core.

**Comment by arabelaa** [comment]
But this is still an issue in combination with application insights - which I find very strange. Can we maybe reference this issue to application insights repository?

**Comment by Tratcher** [comment]
@jkotalik this looks like the issue you investigated that was resolved in a later AI version?

**Comment by jkotalik** [comment]
https://github.com/microsoft/ApplicationInsights-aspnetcore/issues/897
