### ISSUE TITLE
ENC1003 C# Changes made in project will not be applied while the application is running

### ISSUE THREAD

**Issue by jez9999** [aspnet/AspNetCore#13284]
Every time I create a brand new ASP.NET Core 3.0 MVC application project, even if I make no changes, when I his F5 and debug the project I get this error for every C# file:

![image](https://user-images.githubusercontent.com/793830/63364958-7f3c7c00-c36e-11e9-812c-a19afb1cc9f9.png)

This seems like a bug because it's a pointless warning cluttering up the warnings window.  There appears to be no way to get rid of it (because it appears at runtime, I can't even suppress it using the "Suppress warnings" box in the project properties).

**Comment by pranavkm** [comment]
@tmat \ @jaredpar would you know what could be causing this? I can see this when trying to run any ASP.NET Core Web Application using 3.0-preview8 + VS 16.3 Preview 2. More interestingly, this message pops up any time I edit a vanilla console application:

![ENC](https://user-images.githubusercontent.com/174281/63371024-2225d380-c338-11e9-829f-28e589af765c.gif)

Is this expected?

**Comment by jaredpar** [comment]
@jasonmalinowski for IDE routing.

**Comment by jasonmalinowski** [comment]
@jez9999 The warning is saying that you've made edits while the program is running, but until the program is paused and resumed that edit won't be applied. It used to be that edits were entirely blocked if the program was running; this was weakened to allow the edits but they just can't be applied until the program pauses. The warning would go away once you've stopped debugging. Is that what you're seeing?

**Comment by jez9999** [comment]
No - I get the warnings immediately upon hitting F5, with no edits being made.

**Comment by jasonmalinowski** [comment]
OK, got it. @pranavkm's video isn't showing what you're seeing then.

**Comment by pranavkm** [comment]
@jasonmalinowski yup. I was pointing out yet another scenario where it shows up. But as @jez9999 points out, for ASP.NET Core Web applications, the warning pops up as soon as you start debugging.

**Comment by jasonmalinowski** [comment]
@pranavkm: no idea. @tmat will be able to assist further.

**Comment by pranavkm** [comment]
@tmat is there any thing you need to diagnose this further?

**Comment by dotnetshadow** [comment]
I'm getting similar issues with my asp.net core 3.0 preview 9 application on visual studio 2019 preview 3

When I ran it as IISExpress I had the issue, so I decided to delete my .vs folder, bin and obj directories. This seemed to fix the issue, it still shows up the very first time, but after that I am able to debug.

When I try to debug using the kestrel, I get the stubborn error and the above solution doesn't fix this issue. 

The following shows upon pressing F5 
![image](https://user-images.githubusercontent.com/296247/64343319-ac0bb700-d02f-11e9-8ff3-7dcbfa9bf957.png)

Issue seems to be similar to these:
https://developercommunity.visualstudio.com/content/problem/478768/wrongly-getting-message-edits-were-made-to-the-cod.html

https://developercommunity.visualstudio.com/content/problem/439396/aspnet-core-mvc-edits-were-made-to-the-code-which.html

**Comment by pranavkm** [comment]
This is resolved in 16.4 release of Visual Studio. See https://github.com/dotnet/roslyn/pull/38501.

**Comment by karimh93** [comment]
I have the same problem like @jez9999 . Did someone manage how this can be solved?

**Comment by tig** [comment]
@karimh93 - It doesn't fix the fundamental bug which is that the warning is generated in the first place, but you can create a GlobalSuppressions.cs file at the project root, and add the line:

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage(null, "ENC1003")]

This will suppress the error and let you debug.

**Comment by Alex-Horlock** [comment]
If you are like me and you've got here from updating to .Net Core 3.0 and are wondering why you now can't recompile your razor pages on the fly, the solution is that it is now a Nuget package and is explained here: 
https://stackoverflow.com/questions/54600273/net-core-3-0-preview-2-razor-views-dont-automatically-recompile-on-change

**Comment by LConrade** [comment]
I only recently (the last several days) started receving these warning messages after never having received them previously. I have just realised that in the Error List pane, if I change the setting "Build + Intellisense" to just "Build" then I no longer receive these messages, neither in the Error List pane, nor associated with items in Solution Explorer. I must have inadvertently changed that setting without realising. Of course, it means that I no longer receive any other Intellisense-related error notifications but for most of the time I'm not needing to see them. Not sure if that helps others. I think that perhaps this may actually be working as originally designed, though others may think differently. Hope this helps.

**Comment by tmat** [comment]
@LConrade These warnings are new in 16.3. They are supposed to be displayed only in files that support Edit and Continue. Displaying them in other files was not intentional and has been fixed in 16.4.

**Comment by LConrade** [comment]
@tmat Terrific. Thanks for the clarification.
