### ISSUE TITLE
View recompilation appears to be broken

### ISSUE THREAD

**Issue by taori** [aspnet/AspNetCore#14356]
### Describe the bug
Views used to recompile once you make changes to cshtml - that does not appear to be working anymore with 3.0

### To Reproduce
- Create new netcore3.0 mvc web app
- start debugging
- edit Index page, save, reload page

### Expected behavior
changes should be visible, but they are not.

### Reproduction
- checkout https://github.com/taori/Sandbox/tree/netcore3-recompilefails
- Debug ComposableWebApplication
- Change Home/Index.cshtml in main project
- Reload
- And then i get the error.
- MyFeature/Page1 should also work if changing content.

### Screenshots
![grafik](https://user-images.githubusercontent.com/5545184/65484500-82f87c80-de9f-11e9-8f23-f38d1888c8cc.png)

![grafik](https://user-images.githubusercontent.com/5545184/65518842-3b94df00-dee5-11e9-86e6-d0b5f8ac441c.png)

**Comment by taori** [comment]
After digging through the comments in this: https://github.com/aspnet/Blazor/issues/1428 i stumbled into a possible reason. As far as i recall file updates used to work even with debugger attached a while back. Could it be that in order not to break blazor client change updates, mvc auto reload during debugging got cleaved by the changes for blazor? 

Speaking about the comment i have seen here: https://github.com/aspnet/Blazor/issues/1428#issuecomment-422459641

**Comment by u-ashikov** [comment]
It is not a bug, you have to install Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation package. After that you can just call AddRazorRuntimeCompilation() in the ConfigureServices method in the Startup class. 

For more details you can check here: https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.0#runtime-compilation

**Comment by taori** [comment]
@u-ashikov Thanks for pointing it out. Looks like i missed some patch notes.

Currently getting "Cannot find compilation library location for package"-messages. I'll see if i can get rid of them somehow. I hope this isn't the same issue as with 2.x because i came around to trying 3.0 in hopes that this is fixed now.

**Comment by taori** [comment]
Nope. Still not working - is this just broken on my machine? can someone confirm? Adding repro on issue itself.

**Comment by taori** [comment]
@javiercn Yes. Even without debugging i am having this issue.

**Comment by taori** [comment]
@mkArtakMSFT Can you forward the attention to #14359 ?

I've noticed that with a fresh standalone created project with no external RCL the feature works - even when i use the debugger. For the Reproduction i posted it is not working in either case. 

Technically this should be looked at in the scope of #14359 since this appears to be broken by loading plugins but works in principle. If you agree, close this ticket - i'll add the repro sample on the other ticket.

**Comment by pranavkm** [comment]
@taori looks like the other issue was resolved. For your original question @u-ashikov's recommendation is the way to go to get parity with 2.2's compilation.

**Comment by taori** [comment]
@pranavkm It wasn't resolved. He just closed it dismissing the actual issue - changing content breaks the application. I would really appreciate your help with this, since it evidently isn't working

**Comment by taori** [comment]
@pranavkm @javiercn suggested this might be related to missing reference info so i figured i'd look into your repos for alternate ways to add the application parts in a way that works - i found one which has a similar approach to what i am trying in my repro guide. I managed to reproduce the same issue with your application ported to 3.0

Just thought i'd share that it doesnt seem to be related to the missing `*.deps.json` or `*.runtimeconfig.json` in my version since it happens with your ported application as well.

**Comment by taori** [comment]
@pranavkm Correct me if i am wrong, but what i figured from reading sources and the stacktrace is:

- We pass additional ressources to the RazorReferenceManager using the options parameter, code wise this looks like it should be working. this happens [here](https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Razor.RuntimeCompilation/src/RazorReferenceManager.cs#L69)

- The problem is what happens prior to that and makes the recompilation fail, is that earlier in that [file](https://github.com/aspnet/AspNetCore/blob/894d9af96f007340e975e77bbe21c27a5b5be690/src/Mvc/Mvc.Razor.RuntimeCompilation/src/RazorReferenceManager.cs#L65) an attempt is made to resolve references using AssemblyPartExtensions [here](https://github.com/aspnet/AspNetCore/blob/894d9af96f007340e975e77bbe21c27a5b5be690/src/Mvc/Mvc.Razor.RuntimeCompilation/src/AssemblyPartExtensions.cs#L28) which in the end uses [this](https://github.com/dotnet/core-setup/blob/f7f994fea65db39c1792d871c711b07e92fa2560/src/managed/Microsoft.Extensions.DependencyModel/CompilationLibrary.cs#L79) to attempt to resolve the given references.
- I suppose [this](https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.Razor.RuntimeCompilation/src/AssemblyPartExtensions.cs) is where a fix would have to be applied in order for this to work since dependent libraries do not have a compositional programming style and will therefore not be capable of handling non system assemblies without major architecture changes.

You probably have more insight in this, but this is what it looks like to me. At least this explains why the application crashs and burns even when a file that isn't even referenced is changed.

**Comment by taori** [comment]
Ok - So now i have a solution where razor recompile works while debugging for assemblies loaded through AssemblyLoadContext. See https://github.com/taori/Sandbox/tree/netcore3-razorFixedRecompilePOC

Fortunately because ICompilationReferencesProvider is checked first i was able to forward the reference resolution attempt to my custom application parts instead of letting the CompilationLibrary crash the application.

**Comment by taori** [comment]
@pranavkm Sorry if uncalled for PR's are considered rude here. Just wanted to see if it would build. I don't mind if this PR is declined. As mentioned in the PR there are some obvious flaws with it atm + you guys probably prefer to handle delicate parts of the code yourself.

**Comment by pranavkm** [comment]
@taori you generally don't want to copy the deps file to your output directory. MVC will attempt to load references from a deps file if it's present next to an assembly that's added as an `AssemblyPart`. The default reference search path is fairly limited to (https://natemcmaster.com/blog/2017/12/21/netcore-primitives/#depsjson). Not having these files - https://github.com/taori/Sandbox/blob/8ac6378378636fb815245d78f6bea04b7b8bb5df/src/ComposableWebApplication/Plugins/netstandard2.0/ComposableWebApplication.Plugin1.deps.json should resolve your lookup issues. 

If you do need them to be present, using the workaround you have and implementing a `ICompilationReferencesProvider` would be the way to go.

**Comment by taori** [comment]
@pranavkm I verified your suggestion - you are correct. Removing the deps files does fix the lookup issues. Are there some negative sideeffects for removing those files? If not i would just have to look if there is a Property which can omit those deps files from the output folders or set up post build tasks to delete them prior to debugging.

Thanks for the article. I will check it out to find out what exactly is happening. In that case i suspect you are inclinded to decline the PR and just document this behavior? Perhaps the exception should specify this as a potential reason for the exception though, so those who run into the issue immediately know how to fix it without digging in documentation.

**Comment by taori** [comment]
@pranavkm After reading all 3 pages of the article you shared it appears to me like removing deps.json to make it work seems like an unwise decision. And wrapping AssemblyPart just in order to make it work with plugin seems a bit like code smell, no?

**Comment by pranavkm** [comment]
> Are there some negative sideeffects for removing those files? 

Not particularly. If it's not the entry point, it generally shouldn't mater.

> wrapping AssemblyPart just in order to make it work with plugin seems a bit like code smell, no?

We do something like this n the framework, https://github.com/aspnet/AspNetCore/blob/release/3.0/src/Mvc/Mvc/src/MvcServiceCollectionExtensions.cs#L342-L351. It's the intended design for that interface.

A couple more questions to mull about:

* You're running in to issues with the deps file because your app uses runtime compilation. Do you require runtime compilation to be enabled in your application?
* If you simply referenced your plugin projects in the web application rather than attempt to load them at runtime, these wouldn't be issues. Is there a reason you chose to load them at runtime?
