### ISSUE TITLE
Empty BodyReader for controller methods with body

### ISSUE THREAD

**Issue by careless6666** [aspnet/AspNetCore#15009]
Empty BodyReader for controller methods with body ([FromBody] Class model).
When i want get body in UseExceptionHandler from request is empty, but if I remove the parameter from the method, the body will be in the buffer

```
app.UseExceptionHandler(builder =>
            {
                builder.Run(async context =>
                {
                    context.Request.EnableBuffering();

                    var reader = await context.Request.BodyReader.ReadAsync();
                    var buffer = reader.Buffer;
                    var sp = Encoding.UTF8.GetString(buffer.FirstSpan);
                    Console.WriteLine(sp);
                });
            });
```

https://stackoverflow.com/questions/58336505/why-my-request-bodyreader-is-empty-when-i-add-request-parameters-asp-net-core-3

**Comment by javiercn** [comment]
@careless6666 Thanks for contacting us.

I imagine that is caused by the body being consumed by MVC.

@Tratcher Am I right? I'm not sure how UseExceptionHandler works, but I imagine it needs to make a copy of the body or else it won't be available.

**Comment by careless6666** [comment]
It's work  on 2.2

```
app.UseExceptionHandler(builder =>
            {
                builder.Run(async context =>
                {
                    context.Request.EnableBuffering();

                    var bodyStream = new StreamReader(context.Request.Body);
                    bodyStream.BaseStream.Seek(0, SeekOrigin.Begin);
                    var bodyText = bodyStream.ReadToEnd();
                    
                    Console.WriteLine(bodyText);
                });
            });
            
            app.UseMvc();
```

**Comment by davidfowl** [comment]
If you use the same code you had on 2.2 does it still work (using StreamReader instead of BodyReader)?

**Comment by Tratcher** [comment]
Yes, if MVC is consuming the body then buffering needs to be enabled before MVC runs, not just in the exception code path. 2.2 should have the same behavior, unless the exception occured before reading the body?
```
            app.Use((context, next) =>
            {
                    context.Request.EnableBuffering();
                    return next();
            });
            app.UseExceptionHandler(builder =>
            {
                builder.Run(async context =>
                {
                    var bodyStream = new StreamReader(context.Request.Body);
                    bodyStream.BaseStream.Seek(0, SeekOrigin.Begin);
                    var bodyText = bodyStream.ReadToEnd();
                    
                    Console.WriteLine(bodyText);
                });
            });
            
            app.UseMvc();
```

**Comment by mkArtakMSFT** [comment]
@pranavkm has mentioned that this maybe a dupe of a bug we've already fixed.

**Comment by careless6666** [comment]
Yes it's look like a bug. I'm test with behavior now on version SDK Version: 3.1.100-preview2-014466,
and and unfortunately the problem is still relevant. I made 2 mini-projects with a problem reproduction and put it on github.

https://github.com/careless6666/dotnet-core-body

In version 2.0, everything works fine, but in 3.0, unfortunately not, maybe I'm doing something wrong?

**Comment by pranavkm** [comment]
@careless6666 the behavior you were seeing in 2.2 was an unintentional.

 The Newtonsoft.Json based formatters (both in 2.x and 3.0) buffer the request body. However in 2.x this stream wasn't disposed until the request was completed. In 3.0, the default Json formatter does not buffer at all, and the Newtonsoft.Json one disposes the buffer as soon as it's completed with it. 

If you must read the contents of the body in the exception handler, the recommendation would be to call buffer before invoking MVC. See @Tratcher's response here: https://github.com/aspnet/AspNetCore/issues/15009#issuecomment-542291956

**Comment by davidfowl** [comment]
We should make sure this behavior change is documented as such

**Comment by careless6666** [comment]
Thanks @Tratcher, I fixed my test code like you write https://github.com/careless6666/dotnet-core-body/blob/master/WebApplication3.0/Startup.cs, 
get latest build SDK Version: 3.1.100-preview2-014473
send post message 
```curl -X POST \
  http://localhost:5000/test/v1 \
  -H 'Content-Type: application/json' \
   -d '{"test": 123}'```

But why the body is not displayed
```
From handler

From handler end
```
There is no app.UseMvc () in my test project, maybe this is the problem?

**Comment by pranavkm** [comment]
@Tratcher re-opened so you can respond.

**Comment by Tratcher** [comment]
You can remove this line:
https://github.com/careless6666/dotnet-core-body/blob/master/WebApplication3.0/Startup.cs#L55

You still need to seek back to 0 on the request body before reading it.
