### ISSUE TITLE
Visual Studio reports error for razor attributes

### ISSUE THREAD

**Issue by vsfeedback** [aspnet/AspNetCore#16602]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/614257/visual-studio-reports-error-for-razor-attributes.html)._

---
Installed core 3.0 preview 6 on VStudio community ed latest release (16.1.3)
Generated a new project | ASP.NET Core Web Application | .NET Core | ASP.NET Core 3.0 | Blazor

Open Pages | Counter.razor

Error List:
| Code | Description | Line | Note |
| :--- | :--- | :---: | :--|
|vCS0103 | The name 'currentCount' does not exist in the current context | 5 | @currentCount - red undersquiggly |
| CS0103 | The name 'code' does not exist in the current context | 9 | @code - red undersquiggly |
|  | Missing Attribute Name | 7 | @IncrementCount - green undersquggly |

Build and Debug still work, reporting no errors and the page executes as expected including clicking on the buttons and weather display. Just the editor seems to be impacted.

---
#### Visual Studio Feedback System on 6/20/2019, 02:35 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Ailsa Gu [MSFT] on 6/20/2019, 11:13 PM: 

<p>Thank you for sharing your feedback! Our teams prioritize action on product issues with broad customer impact. See details at:  https://docs.microsoft.com/en-us/visualstudio/ide/report-a-problem?view=vs-2017#faq . In case you need answers to common questions or need assisted support, be sure to use  https://visualstudio.microsoft.com/vs/support/ . We’ll keep you posted on any updates to this feedback.</p>

#### Artak Mkrtchyan on 10/16/2019, 08:19 AM: 

<p>Reopening this issue while waiting for a repro project.</p>

#### Visual Studio Feedback System on 10/17/2019, 00:45 PM: 

<p>Our team is unable to investigate this issue further without the requested information. Please update to the latest version of the product and if the problem still occurs, reply with the requested information. Thank you for sharing feedback on Developer Community.</p>

#### Dusty Schofield on 10/17/2019, 03:07 PM: 

(private comment, text removed)
#### Dusty Schofield on 10/17/2019, 03:09 PM: 

<p>please reopen i just added what you need</p>

#### Visual Studio Feedback System on 10/18/2019, 08:08 AM: 

<p>This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.</p>

#### Artak Mkrtchyan on 10/19/2019, 11:53 AM: 

(private comment, text removed)
#### Bill Stamp on 10/28/2019, 05:02 AM: 

(private comment, text removed)

---
#### Visual Studio Feedback System solved on 10/19/2019, 11:54 AM, 0 votes: 

<p>A fix for this issue has been released! Install the most recent release from <a target='_blank' href="https://visualstudio.microsoft.com/downloads/">https://visualstudio.microsoft.com/downloads/</a>. Thank you for providing valuable feedback which has helped improve the product.</p>

#### collinbrittain@gmail.com on 10/21/2019, 08:54 AM: 

<p>Ok it's happening when I rename an existing component. I am able to reproduce consistently.</p><p>1. Open Visual Studio and go to a valid component</p><p>2. Rename the component in solution explorer</p><p>3. Wait a few moments for intellisense to process</p><p>4. \@code block is whited out and has compiler error "the name \@code does not exist in the current context"</p><p>(I added the \ so it wouldn't tag a user named 'code')</p><p>EDIT: It may also be occurring when a razor component is moved in the directory structure.</p>

#### Bill Stamp on 10/28/2019, 05:03 AM: 

(private comment, text removed)
#### Artak Mkrtchyan solved on 10/9/2019, 10:05 PM, 0 votes: 

<p>Thanks for contacting us.<br>
.NET Core 3.0 is now GA. Install the most recent release from <a target='_blank' href="https://visualstudio.microsoft.com/downloads/">https://visualstudio.microsoft.com/downloads/</a> with a corresponding .NET Core 3.0 release and you should not experience these issues any more. Thank you for providing valuable feedback which has helped improve the product.</p>

#### collinbrittain@gmail.com on 10/15/2019, 03:37 PM: 

<p>I thought it was fixed when I updated both the build tools and VS itself (2019) but I am still getting the unrecognized @code block from time to time when I create a new Razor Component.</p><p>I am running on Windows 10, VS Community 2019 and build tools version 16.3.4</p>

#### Artak Mkrtchyan on 10/16/2019, 08:18 AM: 

<p>Thanks for getting back to us.<br>
Can you please clarify what does “from time to time” mean in this case?<br>
Are you seeing this on a new <a target='_blank' href="http://ASP.NET">ASP.NET</a> Core 3.0 project? Also, are you using Blazor Server or Blazor Client project?<br>
Given that we are unable to reproduce this behavior, we will need a small repro project to investigate this.</p>

#### collinbrittain@gmail.com on 10/16/2019, 09:16 AM: 

<p>Yesterday I had one instance where I had to restart VS for it to recognize the @code syntax but it is not happening consistently. So far I can't reproduce... I know that's not very helpful.</p><p>It was in an ASP .NET Core 3.0 project that had already existed before I updated using Blazor Server.</p><p>If you want you close this again that's fine, and I can take note of the scenario if it happens again and post here.</p>

#### Artak Mkrtchyan on 10/17/2019, 00:45 PM: 

<p>Let’s do that. Feel free to get back to us when you have a repro.</p>

#### Aaron Mycar on 10/22/2019, 07:44 PM: 

<p>I just had this happen with a clean install of vs 2019 (latest release)</p><p>Standard create new project with asp.net core with blazor.</p><p>Initially complied fine. Added a component. Included a code section (copy and paste from example with old use of @function ) I changed function to @code. Didnt help any. I heard @function no longer supported.</p><p>Existing pages were fine. New component wasnt.</p><p>I realised I had two instances of VS and the solution open with edits in both. I closed both down. Opened up one instance of the failing solution. It now compiles.</p><p>Not sure if this helps any but perhaps having multi instances of the one solution open with edits in both contributes to the issue.</p>

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us.
@NTaylorMullen can you please look into this? Thanks!

**Comment by NTaylorMullen** [comment]
Multiple VS' same solution open work fine for me 😢. @mkArtakMSFT were you seeing different?

Also karl.mittenzwey would you mind doing the following to provide some additional information:
- Open package manager console in VS and run `dotnet --info` and paste the contents here
- List what versions of Visual Studio you have installed.
- If you're willing to share (it has things like environment variables included in it), run an `msbuild /bl` in the problem Visual Studio's developer command prompt and provide the generated `msbuild.binlog` (it generates in the directory where you run the command)

**Comment by cbrit** [comment]
Hi, just to clarify in case it got lost in the description above:

The issue is now only occurring when I rename or move and existing valid .razor file.

I believe karl.mittenzwey is no longer following the issue.

**Comment by NTaylorMullen** [comment]
@cbrit hmm. I'm not seeing that issue either. Are you able to reproduce on the default Blazor project?

![image](https://i.imgur.com/PLI6NLW.gif)

**Comment by cbrit** [comment]
@NTaylorMullen I just mimicked your steps and the issue is occurring:

![blazorCompilerError](https://user-images.githubusercontent.com/23322838/67719545-024a0600-f9a0-11e9-962f-26d9980416ca.gif)

Also, light theme? Really? 😛

**Comment by NTaylorMullen** [comment]
@cbrit hmm, my bet is that it's been fixed in a future VS update then. When 16.4-preview3 releases can I have you give your scenario a shot there to see if things reproduce?

**Comment by cbrit** [comment]
@NTaylorMullen Yes I will do that. 

In fact, I do see one of the release notes for preview 2 is `Fixed a compiler error when using Blazor or Razor.`. Maybe that was it.

**Comment by cbrit** [comment]
@NTaylorMullen  I installed .NET Core 3.1 Preview 1 + VS 2019 Preview 2 for another issue related to Blazor and I am still seeing the issue _but only under these specific _circumstances:__

1. An _existing_ project has just been opened.
2. Open a razor component. There are no compiler errors.
3. Rename the razor component. Error appears.
4. Close the component tab.
*5. Reopen the component. No error.*
*6. Rename the component. No error.*

It's the same for moving the file in the directory structure.

Proof:

![blazorCompilorError2](https://user-images.githubusercontent.com/23322838/67788703-d16ddd80-fa40-11e9-9ff5-baccc6f60aa3.gif)

**Comment by cbrit** [comment]
P.S. I just noticed you said Preview 3, not 2. I'll wait for it to come out and see.

**Comment by NTaylorMullen** [comment]
> I just noticed you said Preview 3, not 2. I'll wait for it to come out and see. Any idea when it will release?

"soon" ? 😄 Wish I had something more concrete sorry!

**Comment by cbrit** [comment]
@NTaylorMullen I installed Preview 3 and am no longer experiencing the issue. Thanks!
