### ISSUE TITLE
Server side blazor does not trigger @bind update for auto filled input fields

### ISSUE THREAD

**Issue by tn-5** [aspnet/AspNetCore#5594]
I have a test app with a login form with a username and password input, both bound to string properties on the model. It works correctly if I manually enter values in these fields (the string properties get updated from the @bind directive).

If the browser has a cached username / password combination and I select auto fill for these fields, the fields do get filled (visually on the page) but the bound password property does not get updated (the username does). The password field does get filled correctly on the browser, if I make any change to the field (add a space for example), the string password property does get updated.

It looks like whatever event is used to trigger the update does not get processed correctly or does not fire for the auto filled password. I have not tested with other auto filled form fields.

This was tested on Safari & Edge. When exactly the same code is used compiled for client side Blazor it works 100%.

**Comment by tn-5** [comment]
Seems fixed in latest version (core 3 preview 2)

**Comment by blenke** [comment]
It looks like this is still an issue in Edge, works in Chrome. I use the Blazor 3.0 RTM 
I use this code but the variable is never set unless you type something in the input box.

<input type="text" name="dlinput" list="dl" @bind="@myvar" />
<datalist id="dl">
    <option value="one"></option>
    <option value="two"></option>
    <option value="three"></option>
</datalist>
<label>@myvar</label>
@code
{ 
string myvar;
}
