### ISSUE TITLE
NullReferenceException in IISHttpContext

### ISSUE THREAD

**Issue by martincostello** [aspnet/AspNetCore#6075]
### Describe the bug

Since updating a website running in Azure App Service to use ASP.NET Core 2.2.0 with in-process hosting, I've observed a small number of `NullReferenceException`s being thrown via Application Insights.

```
System.NullReferenceException:
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.GetOriginalPath (Microsoft.AspNetCore.Server.IIS, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.InitializeContext (Microsoft.AspNetCore.Server.IIS, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1+<ProcessRequestAsync>d__2.MoveNext (Microsoft.AspNetCore.Server.IIS, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer+<HandleRequest>d__27.MoveNext (Microsoft.AspNetCore.Server.IIS, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60)
```

### To Reproduce

Application experiencing the issue was built from this commit:  martincostello/website@ee2ca4ba02823b97062924b7dc8f313e6278a3f8

### Expected behavior

HTTP request is processed successfully.

### Screenshots

![image](https://user-images.githubusercontent.com/1439341/50333665-fe3a9580-04fd-11e9-95e4-0aeec97d3466.png)

### Additional context
Include the output of `dotnet --info`

**Comment by martincostello** [comment]
Looking at the code in master, it would seem that `GetRawUrlInBytes()` saw `NativeRequest->pRawUrl` to be null or empty, and returned `null`, which then isn't handled by `GetOriginalPath()`.

https://github.com/aspnet/AspNetCore/blob/85e2147ff037cc9950249fbb9d095ad47ec4184a/src/Shared/HttpSys/RequestProcessing/NativeRequestContext.cs#L141-L151

https://github.com/aspnet/AspNetCore/blob/3c09d644cccdb21801f7a79e1188a1a1212de5d9/src/Servers/IIS/src/Microsoft.AspNetCore.Server.IIS/Core/IISHttpContext.cs#L185-L186

**Comment by bartdk-be** [comment]
Same issue over here. Any workaround available ?
Are we sure this is related to the In/OutOfProcess option ?

**Comment by martincostello** [comment]
For me this only started once I switched to in-process hosting after the roll out to Azure App Service of the hosting bundle was completed.

**Comment by jkotalik** [comment]
The frequency of requests there looks like it is coming from the app warmup request after IIS restarts from Always On. To confirm, can you turn off app warmup for a period and see if exceptions are still being thrown?

If that’s the case, the null ref is coming from the warmup request. This behavior is “fine” as the request was fake and it is supposed to startup Program.Main. However, we should more gracefully handle this type of request and not throw.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by martincostello** [comment]
I've disabled _Always On_ and will leave it for a few days to see if it happens again, but it only happened a handful of times in the last 7 days as it is.

**Comment by pakrym** [comment]
@jkotalik or we need to find the module that makes this request and make sure it sets `pRawUrl`.

@martincostello thank you for your help in figuring this out.

**Comment by qqbuby** [comment]
I have also the similar problem, with `get_RemoteIpAddress` 

```
An unhandled exception has occurred while executing the request. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.InitializeRemoteEndpoint()
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.Microsoft.AspNetCore.Http.Features.IHttpConnectionFeature.get_RemoteIpAddress()
   at Microsoft.AspNetCore.Http.Internal.DefaultConnectionInfo.get_RemoteIpAddress()
   at Microsoft.AspNetCore.HttpOverrides.ForwardedHeadersMiddleware.ApplyForwarders(HttpContext context)
   at Microsoft.AspNetCore.HttpOverrides.ForwardedHeadersMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
```

Besides, my app was deployed at Azure app service with autoscale mode.

**Comment by jkotalik** [comment]
@qqbuby do you only see a single request failing per application startup?

**Comment by qqbuby** [comment]
@jkotalik I guess the error  is coming from the app warmup request cause it doesn't happen frequently and I only see a few of error messages per day.

**Comment by pakrym** [comment]
I talked to AppServices folks and this is not how "Always On" works. It's implemented using load balancer sending requests to the app.

**Comment by bgiftge** [comment]
I am seeing this error also localhost. Is it possibly related to the IIS Application Pool setting `AlwaysRunning"`?

**Comment by pakrym** [comment]
@bgiftge possibly, which variation of the error do you see? InitializeRemoteEndpoint or GetOriginalPath ?

**Comment by bgiftge** [comment]
hmm.. maybe I spoke too early. I was convinced that I saw the GetOriginalPath error a couple of times, but I am not finding it in my logs.

**Comment by bgiftge** [comment]
in case this helps, here some of our server logs. The error appears to happen before the first request:
```25 Jan 2019 02:34:04.542
 MyProject.Web Request GET / finished with status 404 in 52.0136ms
25 Jan 2019 02:32:11.237
 MyProject.Web Request POST /api/xyz finished with status 200 in 15098.0613ms
25 Jan 2019 02:31:27.479
 MyProject.Web Unexpected exception in IISHttpServer.HandleRequest.
25 Jan 2019 02:31:25.811
 MyProject.Web MyProject.Web web host has started.
25 Jan 2019 02:31:19.999
 MyProject.Web Using the default authentication scheme MyProject.Application for MyProjectServer
25 Jan 2019 02:31:13.429
 MyProject.Web Starting MyProject.Web web host...
25 Jan 2019 02:31:13.411
 MyProject.Web MyProject.Web web host successfully built.
25 Jan 2019 02:30:56.058
 MyProject.Web Building MyProject.Web web host...
25 Jan 2019 02:30:56.005
 MyProject.Web Configuring MyProject.Web web host build...
25 Jan 2019 02:30:39.169
 MyProject.Web Injecting MyProject.Web secrets...
25 Jan 2019 02:30:38.061
 MyProject.Web Initializing MyProject.Web...```

**Comment by pakrym** [comment]
This is caused by IIS ApplicationInitialization module that doesn't set pRawUrl on Win2012

**Comment by martincostello** [comment]
App Service runs on 2016 these days though, right?

**Comment by pakrym** [comment]
Sorry, I was wrong, this bug was fixed in RS2 update of win 10, AppService is on RS1

**Comment by CycoPH** [comment]
This is still happening in latest 2.2.2 runtime.
[Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer]::Unexpected exception in IISHttpServer.HandleRequest.

Using InProcess hosting with Application Pool Start Mode = AlwaysRunning

**Comment by jkotalik** [comment]
This wasn't fixed in 2.2.2. However, this was fixed in the latest 3.0-preview build of ANCM. If possible, please give that a try.

**Comment by cosmin-ciuc** [comment]
I'm having the same problem. As soon as I changed the hosting model to InProcess I started to get this error.
`Object reference not set to an instance of an object.
    System.NullReferenceException at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.GetOriginalPath
    Microsoft.AspNetCore.Server.IIS, Version=2.2.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
      {"method":"Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.GetOriginalPath","level":0,"assembly":"Microsoft.AspNetCore.Server.IIS, Version=2.2.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","line":0}    
      {"method":"Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.InitializeContext","level":1,"assembly":"Microsoft.AspNetCore.Server.IIS, Version=2.2.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","line":0}`

**Comment by jeremycook** [comment]
I'm glad this will be addressed in 3.0 but will this be addressed in 2.2.x or 2.x?

**Comment by Rugved** [comment]
> I'm glad this will be addressed in 3.0 but will this be addressed in 2.2.x or 2.x?

Were you able to fix this ? We have same issue but no work around in 2.2.2

**Comment by Rugved** [comment]
Update: For us we had preload enabled flag turned on at the Website level. Disabling this fixed the error

**Comment by jeremycook** [comment]
@Rugved I wouldn't say that disabling IIS website preload fixes this issue, but its a valid workaround if you do not need/use preload.

![image](https://user-images.githubusercontent.com/452414/57314230-77521800-70ae-11e9-9ed0-989857337a32.png)

**Comment by bobekhj** [comment]
What implications does this have on the running application? I am running 2.2 and need PreloadEnabled set to true. My app seems to be running without an issue even though I get this error when the application starts.

**Comment by jkotalik** [comment]
It shouldn't have any implication on the running application. It just gives a false positive for an exception.

**Comment by grumpydev-net** [comment]
If I understand this thread correctly, we are supposed to wait for another release and in the meantime this is not causing any harm. But it is really distracting to see these false positives where we expect to see only "real" exceptions. **Is there some middleware that you can provide to catch this condition?** I do not want to filter this on my side, for fear of eating up an authentic failure. TIA

**Comment by martygriffin** [comment]
+1

**Comment by centur** [comment]
Same problem, Azure App Service, asp.net core 2.2
Subscribing to notifications

**Comment by vsadams** [comment]
I am on aspnetcore 3.0 and I still receive this. I am also utilizing InProcess hosting on an App Service.

**Comment by jkotalik** [comment]
@vsadams could you file another issue saying you are hitting this in 3.0?
