### ISSUE TITLE
Console output is not visible in visual studio when using AspNetCoreHostingModel set to InProcess

### ISSUE THREAD

**Issue by yepeekai** [aspnet/AspNetCore#6609]
### Describe the bug
The output of the web application is no longer visible in the output of visual studio (ASP.NET Core Web Server) when using InProcess IIS hosting (webapp.csproj => <AspNetCoreHostingModel>InProcess</AspNetCoreHostingModel>)

### To Reproduce
1. Create a new asp.net core web application in visual studio
2. By default AspNetCoreHostingModel is set to InProcess in the csproj
3. Execute the web app
4. There is no entry available in output to see ASP.NET Core Web Server output

### Expected behavior
The ASP.NET Core Web Server output should be available and we should see the output log of the web app

### Additional context
I am using asp.net core 2.2.1
If I change the value of AspNetCoreHostingModel to OutOfProcess, everything works as expected

**Comment by jkotalik** [comment]
Can you check the Output window "Show output from: Debug"?

**Comment by yepeekai** [comment]
yes that works when you start debugging the web application.  Thanks for that workaround.  But this doesn't work when not in debug as it used to when using outofprocess...

**Comment by BillHiebert** [comment]
@muratg whenrun out of process, Visual Studio inserts a "shim" process between IIS and the users application, The shim starts the user process, connects to stderr\stdout and redirects it to a pipe opened by VS. Inprocess does not have the shim process so it doesn't pick up up the outputs.  Since we start the IIS Express process, we could look into grabbing its output and showing it in the window..

**Comment by jkotalik** [comment]
I think piping the output of iisexpress would just "work". We do it in functional tests today.

**Comment by yepeekai** [comment]
Out of curiosity, is this issue gonna be resolved in the upcomming asp.net core 3 release?

**Comment by BillHiebert** [comment]
It is fixed in the next preview of VS 2019.

**Comment by ryanelian** [comment]
What about VS2017? 😕

**Comment by yepeekai** [comment]
I tried it again today with visual studio 2019 16.0.3 and it only shows:
`Request started: "Get" ... `and` Request ended: ...`
I tried to add the serilog.sinks.debug without any success.

**Comment by jvanderbiest** [comment]
@yepeekai still not working with 16.1.5

As a workaround you can modify the project properties, navigate to `Debug`, select the ÌIS Express` profile and select `Out Of Process` as hosting model. It's a change that is local for your machine so you will be still running InProcess in production.

![image](https://user-images.githubusercontent.com/3985995/62357860-28cce200-b514-11e9-9fda-adac3cce567c.png)

**Comment by fragilerus** [comment]
@BillHiebert Still not fixed in VS 2019 16.1.6. This is a bit of a drag on debugging if InProcess is specifically required (Debug is a workaround). Any thoughts on resolution?

**Comment by BillHiebert** [comment]
@fragilerus this should be working in that build. I assume you are using IIS Express for hosting?

**Comment by jkotalik** [comment]
@BillHiebert I believe this is still an issue with 2.2. I have a proposed fix here: https://github.com/aspnet/AspNetCore/pull/10084, but we haven't patched it yet.

**Comment by jkotalik** [comment]
This, however, does work in 3.0.

**Comment by yepeekai** [comment]
3.0 is out and we updated to it and it works.
