### ISSUE TITLE
[Blazor 0.9.0]  The specified framework 'Microsoft.NETCore.App', version '2.0.0' was not found.

### ISSUE THREAD

**Issue by ctrl-alt-d** [aspnet/AspNetCore#8440]
#### Versions: 

* Microsoft.AspNetCore.Blazor  0.9.0-preview3-19154-02 
* Microsoft.AspNetCore.Blazor.Build 0.9.0-preview3-19154-02
* Docker `mcr.microsoft.com/dotnet/core/sdk:3.0` ( netcore3 preview3 `DOTNET_SDK_VERSION=3.0.100-preview3-010431`)

#### Issue: 

On `dotnet build` error appear:

```
It was not possible to find any compatible framework version
  The specified framework 'Microsoft.NETCore.App', version '2.0.0' was not found.
```

### To Reproduce

1. Create a blazor hosted app from template ( I didn't try with other confs)
2. Try to compile inside docker sdk, the error will appear.

### All trace:

```
root@119849f1deae:/# dotnet build
Microsoft (R) Build Engine version 16.0.443+g5775d0d6bb for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Persisting no-op dg to /tmp8.Server/obj/tmp8.Server.csproj.nuget.dgspec.json
  Persisting no-op dg to /tmp8.Client/obj/tmp8.Client.csproj.nuget.dgspec.json
  Restore completed in 17.1 sec for /tmp8.Client/tmp8.Client.csproj.
  Persisting no-op dg to /tmp8.Shared/obj/tmp8.Shared.csproj.nuget.dgspec.json
  Restore completed in 5.87 ms for /tmp8.Shared/tmp8.Shared.csproj.
  Restore completed in 23.16 sec for /tmp8.Server/tmp8.Server.csproj.
/usr/share/dotnet/sdk/3.0.100-preview3-010431/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(151,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview [/tmp8.Server/tmp8.Server.csproj]/usr/share/dotnet/sdk/3.0.100-preview3-010431/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(151,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview [/tmp8.Client/tmp8.Client.csproj]
  tmp8.Shared -> /tmp8.Shared/bin/Debug/netstandard2.0/tmp8.Shared.dll
  tmp8.Client -> /tmp8.Client/bin/Debug/netstandard2.0/tmp8.Client.dll
  It was not possible to find any compatible framework version
  The specified framework 'Microsoft.NETCore.App', version '2.0.0' was not found.
    - Check application dependencies and target a framework version installed at:
        /usr/share/dotnet/
    - The .NET Core Runtime and SDK can be installed from:
        https://aka.ms/dotnet-download
    - The following versions are installed:
        3.0.0-preview3-27503-5 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
    - Installing .NET Core prerequisites might help resolve this problem:
        https://go.microsoft.com/fwlink/?linkid=2063370
/root/.nuget/packages/microsoft.aspnetcore.blazor.build/0.9.0-preview3-19154-02/targets/Blazor.MonoRuntime.targets(439,5): error MSB3073: The command "dotnet "/root/.nuget/packages/microsoft.aspnetcore.blazor.mono/0.8.0-preview-20190204.1/build/netstandard1.0/../../tools/illink/illink.dll" -l none --verbose --strip-security true --exclude-feature com --exclude-feature sre -v false -c link -u link -b true -d "/root/.nuget/packages/microsoft.aspnetcore.blazor.mono/0.8.0-preview-20190204.1/build/netstandard1.0/../../tools/mono/bcl/" -d "/root/.nuget/packages/microsoft.aspnetcore.blazor.mono/0.8.0-preview-20190204.1/build/netstandard1.0/../../tools/mono/bcl/Facades/" -o "/tmp8.Client/obj/Debug/netstandard2.0/blazor/linker/" -x "/root/.nuget/packages/microsoft.aspnetcore.blazor.build/0.9.0-preview3-19154-02/targets/BuiltInBclLinkerDescriptor.xml" -x "/tmp8.Client/obj/Debug/netstandard2.0/blazor/linker.descriptor.xml" -a "/root/.nuget/packages/microsoft.aspnetcore.blazor/0.9.0-preview3-19154-02/lib/netstandard2.0/Microsoft.AspNetCore.Blazor.dll" -a "/root/.nuget/packages/microsoft.aspnetcore.components/3.0.0-preview3-19153-02/lib/netstandard2.0/Microsoft.AspNetCore.Components.dll" -a "/root/.nuget/packages/microsoft.aspnetcore.components.browser/3.0.0-preview3-19153-02/lib/netstandard2.0/Microsoft.AspNetCore.Components.Browser.dll" -a "/root/.nuget/packages/microsoft.extensions.dependencyinjection/3.0.0-preview3.19153.1/lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.dll" -a "/root/.nuget/packages/microsoft.extensions.dependencyinjection.abstractions/3.0.0-preview3.19153.1/lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.Abstractions.dll" -a "/root/.nuget/packages/microsoft.jsinterop/3.0.0-preview3.19153.1/lib/netstandard2.0/Microsoft.JSInterop.dll" -a "/root/.nuget/packages/mono.webassembly.interop/3.0.0-preview3.19153.1/lib/netstandard2.0/Mono.WebAssembly.Interop.dll" -a "/root/.nuget/packages/system.componentmodel.annotations/4.6.0-preview3.19128.7/lib/netstandard2.0/System.ComponentModel.Annotations.dll" -a "/tmp8.Shared/bin/Debug/netstandard2.0/tmp8.Shared.dll" -a "/tmp8.Client/obj/Debug/netstandard2.0/tmp8.Client.dll"" exited with code 150. [/tmp8.Client/tmp8.Client.csproj]

Build FAILED.

/root/.nuget/packages/microsoft.aspnetcore.blazor.build/0.9.0-preview3-19154-02/targets/Blazor.MonoRuntime.targets(439,5): error MSB3073: The command "dotnet "/root/.nuget/packages/microsoft.aspnetcore.blazor.mono/0.8.0-preview-20190204.1/build/netstandard1.0/../../tools/illink/illink.dll" -l none --verbose --strip-security true --exclude-feature com --exclude-feature sre -v false -c link -u link -b true -d "/root/.nuget/packages/microsoft.aspnetcore.blazor.mono/0.8.0-preview-20190204.1/build/netstandard1.0/../../tools/mono/bcl/" -d "/root/.nuget/packages/microsoft.aspnetcore.blazor.mono/0.8.0-preview-20190204.1/build/netstandard1.0/../../tools/mono/bcl/Facades/" -o "/tmp8.Client/obj/Debug/netstandard2.0/blazor/linker/" -x "/root/.nuget/packages/microsoft.aspnetcore.blazor.build/0.9.0-preview3-19154-02/targets/BuiltInBclLinkerDescriptor.xml" -x "/tmp8.Client/obj/Debug/netstandard2.0/blazor/linker.descriptor.xml" -a "/root/.nuget/packages/microsoft.aspnetcore.blazor/0.9.0-preview3-19154-02/lib/netstandard2.0/Microsoft.AspNetCore.Blazor.dll" -a "/root/.nuget/packages/microsoft.aspnetcore.components/3.0.0-preview3-19153-02/lib/netstandard2.0/Microsoft.AspNetCore.Components.dll" -a "/root/.nuget/packages/microsoft.aspnetcore.components.browser/3.0.0-preview3-19153-02/lib/netstandard2.0/Microsoft.AspNetCore.Components.Browser.dll" -a "/root/.nuget/packages/microsoft.extensions.dependencyinjection/3.0.0-preview3.19153.1/lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.dll" -a "/root/.nuget/packages/microsoft.extensions.dependencyinjection.abstractions/3.0.0-preview3.19153.1/lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.Abstractions.dll" -a "/root/.nuget/packages/microsoft.jsinterop/3.0.0-preview3.19153.1/lib/netstandard2.0/Microsoft.JSInterop.dll" -a "/root/.nuget/packages/mono.webassembly.interop/3.0.0-preview3.19153.1/lib/netstandard2.0/Mono.WebAssembly.Interop.dll" -a "/root/.nuget/packages/system.componentmodel.annotations/4.6.0-preview3.19128.7/lib/netstandard2.0/System.ComponentModel.Annotations.dll" -a "/tmp8.Shared/bin/Debug/netstandard2.0/tmp8.Shared.dll" -a "/tmp8.Client/obj/Debug/netstandard2.0/tmp8.Client.dll"" exited with code 150. [/tmp8.Client/tmp8.Client.csproj]
    0 Warning(s)
    1 Error(s)
```

### Workaround:

* opt1: Install sdk 2 into docker.
* opt2: create a fake sdk 2 linking sdk to itself ( `ln -s ./3.0.0-preview3-27503-5 ./2.2.0` )

**Comment by SSSikora** [comment]
Check the section titled, "Troubleshooting your first build" - maybe this is simila to your issue.

https://devblogs.microsoft.com/premier-developer/exploring-blazor-with-visual-studio-2019/

-Scott

**Comment by ctrl-alt-d** [comment]
Hi Mr. @SSSikora, yes, it looks like the same issue. 

I would like to know if, officially, Blazor needs Sdk 2 on Sdk 3.

Thanks, best regards.

**Comment by ctrl-alt-d** [comment]
I guess this is related with: https://github.com/aspnet/AspNetCore/issues/6726

**Comment by ctrl-alt-d** [comment]
Ok, I found the answer on [release notes, Known issues](https://devblogs.microsoft.com/aspnet/blazor-0-8-0-experimental-release-now-available/):

> "It was not possible to find any compatible framework version. The specified framework 'Microsoft.NETCore.App', version '2.0.0' was not found.": You may see this error when building a Blazor app because the IL linker currently requires .NET Core 2.x to run. To work around this issue, either install .NET Core 2.2 or disable IL linking by setting the <BlazorLinkOnBuild>false</BlazorLinkOnBuild> property in your project file.

It looks this issue also affect 0.9.0: https://github.com/aspnet/AspNetCore/issues/6726

**Comment by ctrl-alt-d** [comment]
I Reopen the issue because I guess [Releases notes 0.9.0 -  know issues section](https://github.com/aspnet/Blazor/releases/tag/0.9.0) should be fixed, must include:

> "The specified framework 'Microsoft.NETCore.App', version '2.0.0' was not found. ": You may see this error when building a Blazor app because the IL linker currently requires .NET Core 2.x to run. To work around this issue, either install .NET Core 2.2 or disable IL linking by setting the <BlazorLinkOnBuild>false</BlazorLinkOnBuild> property in your project file

**Comment by Rymix** [comment]
I got the same issue than you.
I solved that by : Deleting all my Nuget package on windows + Update again all nugets from 0.8.0 to 0.9.0

**Comment by jdgwf** [comment]
I'm also getting this with dotnetcore3 preview via snap on Ubuntu linux. Snap won't allow a side-by-side install of 3 and 2.2. Builds are getting the following:
```

jeff@jdg-ubuntu:~/Development/dotnet/test/test.Client$ dotnet build
Microsoft (R) Build Engine version 16.0.443+g5775d0d6bb for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Persisting no-op dg to /home/jeff/Nextcloud/Development/dotnet/test/test.Shared/obj/test.Shared.csproj.nuget.dgspec.json
  Persisting no-op dg to /home/jeff/Nextcloud/Development/dotnet/test/test.Client/obj/test.Client.csproj.nuget.dgspec.json
  Restore completed in 32.85 ms for /home/jeff/Nextcloud/Development/dotnet/test/test.Shared/test.Shared.csproj.
  Restore completed in 179.81 ms for /home/jeff/Nextcloud/Development/dotnet/test/test.Client/test.Client.csproj.
/snap/dotnet-sdk/30/sdk/3.0.100-preview3-010431/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(151,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview [/home/jeff/Nextcloud/Development/dotnet/test/test.Client/test.Client.csproj]
  test.Shared -> /home/jeff/Nextcloud/Development/dotnet/test/test.Shared/bin/Debug/netstandard2.0/test.Shared.dll
  test.Client -> /home/jeff/Nextcloud/Development/dotnet/test/test.Client/bin/Debug/netcoreapp3.0/test.Client.dll
  It was not possible to find any compatible framework version
  The specified framework 'Microsoft.NETCore.App', version '2.0.0' was not found.
    - Check application dependencies and target a framework version installed at:
        /snap/dotnet-sdk/30/
    - The .NET Core Runtime and SDK can be installed from:
        https://aka.ms/dotnet-download
    - The following versions are installed:
        3.0.0-preview3-27503-5 at [/snap/dotnet-sdk/30/shared/Microsoft.NETCore.App]
    - Installing .NET Core prerequisites might help resolve this problem:
        https://go.microsoft.com/fwlink/?linkid=2063370
/home/jeff/.nuget/packages/microsoft.aspnetcore.blazor.build/0.9.0-preview3-19154-02/targets/Blazor.MonoRuntime.targets(439,5): error MSB3073: The command "dotnet "/home/jeff/.nuget/packages/microsoft.aspnetcore.blazor.mono/0.8.0-preview-20190204.1/build/netstandard1.0/../../tools/illink/illink.dll" -l none --verbose --strip-security true --exclude-feature com --exclude-feature sre -v false -c link -u link -b true -d "/home/jeff/.nuget/packages/microsoft.aspnetcore.blazor.mono/0.8.0-preview-20190204.1/build/netstandard1.0/../../tools/mono/bcl/" -d "/home/jeff/.nuget/packages/microsoft.aspnetcore.blazor.mono/0.8.0-preview-20190204.1/build/netstandard1.0/../../tools/mono/bcl/Facades/" -o "/home/jeff/Nextcloud/Development/dotnet/test/test.Client/obj/Debug/netcoreapp3.0/blazor/linker/" -x "/home/jeff/.nuget/packages/microsoft.aspnetcore.blazor.build/0.9.0-preview3-19154-02/targets/BuiltInBclLinkerDescriptor.xml" -x "/home/jeff/Nextcloud/Development/dotnet/test/test.Client/obj/Debug/netcoreapp3.0/blazor/linker.descriptor.xml" -a "/home/jeff/.nuget/packages/microsoft.aspnetcore.blazor/0.9.0-preview3-19154-02/lib/netstandard2.0/Microsoft.AspNetCore.Blazor.dll" -a "/home/jeff/.nuget/packages/microsoft.aspnetcore.components/3.0.0-preview3-19153-02/lib/netstandard2.0/Microsoft.AspNetCore.Components.dll" -a "/home/jeff/.nuget/packages/microsoft.aspnetcore.components.browser/3.0.0-preview3-19153-02/lib/netstandard2.0/Microsoft.AspNetCore.Components.Browser.dll" -a "/home/jeff/.nuget/packages/microsoft.extensions.dependencyinjection/3.0.0-preview3.19153.1/lib/netcoreapp3.0/Microsoft.Extensions.DependencyInjection.dll" -a "/home/jeff/.nuget/packages/microsoft.extensions.dependencyinjection.abstractions/3.0.0-preview3.19153.1/lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.Abstractions.dll" -a "/home/jeff/.nuget/packages/microsoft.jsinterop/3.0.0-preview3.19153.1/lib/netstandard2.0/Microsoft.JSInterop.dll" -a "/home/jeff/.nuget/packages/mono.webassembly.interop/3.0.0-preview3.19153.1/lib/netstandard2.0/Mono.WebAssembly.Interop.dll" -a "/home/jeff/Nextcloud/Development/dotnet/test/test.Shared/bin/Debug/netstandard2.0/test.Shared.dll" -a "/home/jeff/Nextcloud/Development/dotnet/test/test.Client/obj/Debug/netcoreapp3.0/test.Client.dll"" exited with code 150. [/home/jeff/Nextcloud/Development/dotnet/test/test.Client/test.Client.csproj]

Build FAILED.

/home/jeff/.nuget/packages/microsoft.aspnetcore.blazor.build/0.9.0-preview3-19154-02/targets/Blazor.MonoRuntime.targets(439,5): error MSB3073: The command "dotnet "/home/jeff/.nuget/packages/microsoft.aspnetcore.blazor.mono/0.8.0-preview-20190204.1/build/netstandard1.0/../../tools/illink/illink.dll" -l none --verbose --strip-security true --exclude-feature com --exclude-feature sre -v false -c link -u link -b true -d "/home/jeff/.nuget/packages/microsoft.aspnetcore.blazor.mono/0.8.0-preview-20190204.1/build/netstandard1.0/../../tools/mono/bcl/" -d "/home/jeff/.nuget/packages/microsoft.aspnetcore.blazor.mono/0.8.0-preview-20190204.1/build/netstandard1.0/../../tools/mono/bcl/Facades/" -o "/home/jeff/Nextcloud/Development/dotnet/test/test.Client/obj/Debug/netcoreapp3.0/blazor/linker/" -x "/home/jeff/.nuget/packages/microsoft.aspnetcore.blazor.build/0.9.0-preview3-19154-02/targets/BuiltInBclLinkerDescriptor.xml" -x "/home/jeff/Nextcloud/Development/dotnet/test/test.Client/obj/Debug/netcoreapp3.0/blazor/linker.descriptor.xml" -a "/home/jeff/.nuget/packages/microsoft.aspnetcore.blazor/0.9.0-preview3-19154-02/lib/netstandard2.0/Microsoft.AspNetCore.Blazor.dll" -a "/home/jeff/.nuget/packages/microsoft.aspnetcore.components/3.0.0-preview3-19153-02/lib/netstandard2.0/Microsoft.AspNetCore.Components.dll" -a "/home/jeff/.nuget/packages/microsoft.aspnetcore.components.browser/3.0.0-preview3-19153-02/lib/netstandard2.0/Microsoft.AspNetCore.Components.Browser.dll" -a "/home/jeff/.nuget/packages/microsoft.extensions.dependencyinjection/3.0.0-preview3.19153.1/lib/netcoreapp3.0/Microsoft.Extensions.DependencyInjection.dll" -a "/home/jeff/.nuget/packages/microsoft.extensions.dependencyinjection.abstractions/3.0.0-preview3.19153.1/lib/netstandard2.0/Microsoft.Extensions.DependencyInjection.Abstractions.dll" -a "/home/jeff/.nuget/packages/microsoft.jsinterop/3.0.0-preview3.19153.1/lib/netstandard2.0/Microsoft.JSInterop.dll" -a "/home/jeff/.nuget/packages/mono.webassembly.interop/3.0.0-preview3.19153.1/lib/netstandard2.0/Mono.WebAssembly.Interop.dll" -a "/home/jeff/Nextcloud/Development/dotnet/test/test.Shared/bin/Debug/netstandard2.0/test.Shared.dll" -a "/home/jeff/Nextcloud/Development/dotnet/test/test.Client/obj/Debug/netcoreapp3.0/test.Client.dll"" exited with code 150. [/home/jeff/Nextcloud/Development/dotnet/test/test.Client/test.Client.csproj]
    0 Warning(s)
    1 Error(s)

```
Shared builds, Client does not, Server does not due to Client ability. 
Really excited about this technology; waiting to get it working.

P.S. had similar trouble via command line on Win10

**Comment by ctrl-alt-d** [comment]
@jdgwf , This is because `/tools/illink`. Maybe you can try it [disabling linker](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/razor-components/configure-linker?view=aspnetcore-3.0)? In project file add:

```
<PropertyGroup>
  <BlazorLinkOnBuild>false</BlazorLinkOnBuild>
</PropertyGroup>
```

Do you have 2 also alternatives:
* Install sdk2.2 framework.
* Fake sdk2.2 framework copying sdk 3 as 2 ( `ln -s /home/dani/dotnet/sdk/3.0.100-preview3-010431 /home/dani/dotnet/sdk/2.2.0` )

**Comment by jdgwf** [comment]
Wonderful! Thank you! I'm good to go!

**Comment by mkArtakMSFT** [comment]
This is now fixed!

**Comment by isc30** [comment]
still having this issue with the official docker image
`mcr.microsoft.com/dotnet/core/sdk:3.0`
