### ISSUE TITLE
Enabling Razor file compilation in 3.0 causes InvalidOperationException when reloading page with changes

### ISSUE THREAD

**Issue by bjornpaulstrom** [aspnet/AspNetCore#8868]
### Describe the bug
Changes to .cshtml files generates InvalidOperationException when reloading the page if RazorRuntimeCompilation is enabled.

### To Reproduce

1. Start new 3.0 MVC project
2. Follow steps at https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.0 to enable runtime compilation.
3. Start project
4. Make change to index.cshtml
5. Reload page

### Expected behavior
The changes should be reflected on the page.

### Screenshots
When refreshing it generates this error:
![image](https://user-images.githubusercontent.com/15799703/55113439-8624d280-50df-11e9-8eb7-b4da8ad09114.png)

### Additional context
Installing the latest available Microsoft.AspNetCore.Antiforgery package generates a new error:
![image](https://user-images.githubusercontent.com/15799703/55113642-23800680-50e0-11e9-9497-aac68da51c54.png)

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/AspNetCore/issues/7966 which is getting fixed in the preview4 release. For preview3, you'd have to set `<PreserveCompilationReferences>true</PreserveCompilationReferences>` in your project file.

**Comment by WilsonDotNet** [comment]
I am using preview 5 and have done everything noted and still get this antiforgery error.
