### ISSUE TITLE
Can't build AspNetCore source with VS 2019 RTM

### ISSUE THREAD

**Issue by adrianwright109** [aspnet/AspNetCore#9024]
When I follow the instructions in `docs/BuildFromSource.md` and run `.\restore.cmd` it tells me that I don't have the correct version of Visual Studio 2019 installed"

The screenshot below shows I have Visual Studio Community 2019 16.0 RTM installed.

![image](https://user-images.githubusercontent.com/47532258/55468482-5c960a80-55fb-11e9-8c58-6fb80f2d2064.png)

If I run `.\eng\scripts\InstallVisualStudio.ps1 -Edition Community` as suggested by the error message in the screenshot above; it launches the the Visual Studio Installer and tries to modify my existing installation of Visual Studio Community 2019 16.0 RTM.

Currently Visual Studio Community 2019 16.0 RTM is the same as Visual Studio Community 2019 Preview 5 

![image](https://user-images.githubusercontent.com/47532258/55469260-0b871600-55fd-11e9-8587-c6bd1b24276a.png)

At the moment the only way to get around this Visual Studio version check in `.\restore.cmd` is to install Visual Studio Community 2019 Preview 5 as the check seems to be looking for a preview version.
**N.B. Before I installed Visual Studio Community 2019 16.0 RTM when I ran `.\eng\scripts\InstallVisualStudio.ps1 -Edition Community` it wanted to install Visual Studio Community 2019 Preview 5**

Going forward are we going to be getting any more Preview versions of Visual Studio 2019 now that it has RTM'd or will it be the RTM version plus subsequent servicing updates?

**Comment by Eilon** [comment]
I think VS2019 RTM (incl. Community Edition) are all you should need. But perhaps there's a bug in the setup scripts, which we will investigate.

**Comment by natemcmaster** [comment]
Fixed with https://github.com/aspnet/AspNetCore/pull/9057

**Comment by Eilon** [comment]
Thanks, @natemcmaster !

**Comment by adrianwright109** [comment]
Hi,

Sorry but this isn't fixed.

I have just updated my `AspNetCore` fork so I'm currently even with master.

![image](https://user-images.githubusercontent.com/47532258/55613830-8712cf80-5783-11e9-8453-4f375a9e801c.png)

I have run `.\restore.cmd` and I'm still getting the same error:

![image](https://user-images.githubusercontent.com/47532258/55613914-bcb7b880-5783-11e9-913c-760a4fe2551b.png)

**Comment by Eilon** [comment]
Re-opening for @natemcmaster to take a look at

**Comment by natemcmaster** [comment]
And did you run InstallVisualStudio.ps1 ?

**Comment by adrianwright109** [comment]
I must apologise - my bad.  I did run `InstallVisualStudio.ps1 -Edition Community` and it loaded up the VS Installer with my original VS 2019 RTM installation showing the following workloads were installed:

- ASP.NET and web development
- .NET  desktop development
- Desktop development with C++
- Visual Studio extension development
- .NET Core cross-platform development

It appeared like that I had everything installed; but I didn't.

I have re-run the command and since noticed the **Modify** button!  I have just installed 53 missing packages!  Obviously the workloads I had were using the default set of components and they have been customised to include more than the default.
