### ISSUE TITLE
ASP.NET Core hosted Blazor app fails to run in Docker

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#9704]
Repro steps:
- Create a new Blazor (ASP.NET Core hosted) app with the Preview 4 bits
- Build and run - it works
- Right click, Add Docker support (Linux)
- Build and run on Docker Linux

Actual result:

```
Unhandled Exception: System.ArgumentException: The directory name  is invalid.
Parameter name: path
   at System.IO.FileSystemWatcher.CheckPathValidity(String path)
   at System.IO.FileSystemWatcher..ctor(String path)
   at Microsoft.AspNetCore.Builder.AutoRebuildExtensions.WatchFileSystem(BlazorConfig config, Action onWrite)
   at Microsoft.AspNetCore.Builder.BlazorApplicationBuilderExtensions.UseBlazor(IApplicationBuilder app, BlazorOptions options)
   at BlazorDocker.Server.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in C:\Users\daroth\Source\Repos\BlazorDocker\BlazorDocker.Server\Startup.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.Internal.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at BlazorDocker.Server.Program.Main(String[] args) in C:\Users\daroth\Source\Repos\BlazorDocker\BlazorDocker.Server\Program.cs:line 11
```

More repro steps:
- Disable Blazor auto-build by adding `<BlazorRebuildOnFileChange>false</BlazorRebuildOnFileChange>` to the client project file.
- Build and run the app

Actual result:

```
Unhandled Exception: System.ArgumentException: The path must be absolute.
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
Parameter name: root
   at Microsoft.AspNetCore.Builder.BlazorApplicationBuilderExtensions.UseBlazor(IApplicationBuilder app, BlazorOptions options)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at BlazorDocker.Server.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in C:\Users\daroth\Source\Repos\BlazorDocker\BlazorDocker.Server\Startup.cs:line 43
   at Microsoft.AspNetCore.Builder.BlazorApplicationBuilderExtensions.UseBlazor(IApplicationBuilder app, BlazorOptions options)
--- End of stack trace from previous location where exception was thrown ---
   at BlazorDocker.Server.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in C:\Users\daroth\Source\Repos\BlazorDocker\BlazorDocker.Server\Startup.cs:line 43
   at Microsoft.AspNetCore.Hosting.Internal.ConventionBasedStartup.Configure(IApplicationBuilder app)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
[41m[1m[37mcrit[39m[22m[49m: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
      Application startup exception
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
System.ArgumentException: The path must be absolute.
Parameter name: root
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Builder.BlazorApplicationBuilderExtensions.UseBlazor(IApplicationBuilder app, BlazorOptions options)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at BlazorDocker.Server.Program.Main(String[] args) in C:\Users\daroth\Source\Repos\BlazorDocker\BlazorDocker.Server\Program.cs:line 11
   at BlazorDocker.Server.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in C:\Users\daroth\Source\Repos\BlazorDocker\BlazorDocker.Server\Startup.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.Internal.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```

**Comment by CESARDELATORRE** [comment]
Still fails because the generated file BlazorASPNETCoreHosted.Client.blazor.config is generating a filepath with Windows style. Since this is Docker on Linux, it fails:

```
BlazorASPNETCoreHosted.Client.blazor.config:

D:\DevSpikes\BlazorASPNETCoreHosted\BlazorASPNETCoreHosted.Client\BlazorASPNETCoreHosted.Client.csproj
bin\Debug\netstandard2.0\BlazorASPNETCoreHosted.Client.dll
autorebuild:true
debug:true
```

I tried to remove the Windows style and have it as a relative path, and I was able to run it on Docker okay:

```
BlazorASPNETCoreHosted.Client.blazor.config:

BlazorASPNETCoreHosted.Client.csproj
bin\Debug\netstandard2.0\BlazorASPNETCoreHosted.Client.dll
autorebuild:true
debug:true
```

However, whenever I compile this project from Visual Studio, this path is re-generated, so it is a bug that needs to be fixed.

**Comment by SteveSandersonMS** [comment]
@CESARDELATORRE I agree this is a bug we should fix. However the fix won't be out before Build, because it's too late.

In the meantime, you might be able to use a hacky workaround like the following. To have your custom `.blazor.config` regenerated on each build, add something like the following to your client app's `.csproj`:

```xml
  <Target Name="FixBlazorConfigForDocker" AfterTargets="GenerateBlazorMetadataFile">
    <WriteLinesToFile File="$(BlazorMetadataFilePath)" Lines="BlazorASPNETCoreHosted.Client.csproj" Overwrite="true" Encoding="Unicode"/>
    <WriteLinesToFile File="$(BlazorMetadataFilePath)" Lines="$(OutDir)$(AssemblyName).dll" Overwrite="false" Encoding="Unicode"/>
    <WriteLinesToFile File="$(BlazorMetadataFilePath)" Condition="'$(BlazorRebuildOnFileChange)'=='true'" Lines="autorebuild:true" Overwrite="false" Encoding="Unicode"/>
    <WriteLinesToFile File="$(BlazorMetadataFilePath)" Condition="'$(BlazorEnableDebugging)'=='true'" Lines="debug:true" Overwrite="false" Encoding="Unicode"/>
  </Target>
```

This will produce the same content that you showed above, i.e.:

```
BlazorASPNETCoreHosted.Client.csproj
bin\Debug\netstandard2.0\BlazorASPNETCoreHosted.Client.dll
autorebuild:true
debug:true
```

**Comment by CESARDELATORRE** [comment]
@SteveSandersonMS - Thanks Steve. That hack in the client `.csproj` works perfectly when running the app on RELEASE mode from Visual Studio even re-generating the build from scratch (I tested it deleting /bin /obj folders), which is good so I don't need to manually fix the `.blazor.config` file. :) 

However, if you run the project in DEBUG mode (F5) from Visual Studio, it still impacts braking the app and you still get the following exception:

System.ArgumentException
  HResult=0x80070057
  Message=**The directory name  is invalid.**
  Source=System.IO.FileSystem.Watcher
  StackTrace:
   at System.IO.FileSystemWatcher.CheckPathValidity(String path)
   at System.IO.FileSystemWatcher..ctor(String path)
   at Microsoft.AspNetCore.Builder.AutoRebuildExtensions.WatchFileSystem(BlazorConfig config, Action onWrite)
   at Microsoft.AspNetCore.Builder.BlazorApplicationBuilderExtensions.UseBlazor(IApplicationBuilder app, BlazorOptions options)
   at BlazorSentimentAnalysis.Server.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in D:\DevSpikes\ScalableSentimentAnalysisBlazorWebApp-Docker\BlazorSentimentAnalysis.Server\Startup.cs:line 60

So the fix on the generation code for the bug must be impacting additional DEBUG features that don't understand now the relative path. 

In any case, thanks a lot for the workarounds. I can manage with these workarounds until the bug is fixed, eventually. Thanks! 👍

**Comment by hero115** [comment]
The fix above worked for me on Preview5 , I am not sure if this is related to the issue, but I also get a System.FileNotFoundException /src/BlazorASPNETCoreHosted.Client/wwwroot when trying this with preview6 and adjusting the docer images to use preview6 as well. With or without the target, the issue remains the same. Let me know if I should open a new seperate issue. Thanks.

**Comment by RealTadango** [comment]
There is an issue with Preview6 now: 


Unhandled Exception: System.ArgumentException: The path must be absolute.
Parameter name: root
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Microsoft.AspNetCore.Builder.BlazorHostingEndpointRouteBuilderExtensions.MapFallbackToClientSideBlazor(IEndpointRouteBuilder endpoints, String clientAssemblyFilePath, String pattern, String filePath)
   at Microsoft.AspNetCore.Builder.BlazorHostingEndpointRouteBuilderExtensions.MapFallbackToClientSideBlazor[TClientApp](IEndpointRouteBuilder endpoints, String pattern, String filePath)
   at Favorites.Server.Startup.<>c.<Configure>b__4_0(IEndpointRouteBuilder endpoints) in C:\Users\Herman\Source\Workspaces\Default\Favorites\Favorites.Server\Startup.cs:line 72
   at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action`1 configure)
   at Favorites.Server.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in C:\Users\Herman\Source\Workspaces\Default\Favorites\Favorites.Server\Startup.cs:line 73
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)

**Comment by rchande** [comment]
We're also hitting this in dotnet/try:
```
 System.ArgumentException: The path must be absolute.
Parameter name: root
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Microsoft.AspNetCore.Builder.BlazorHostingEndpointRouteBuilderExtensions.MapFallbackToClientSideBlazor(IEndpointRouteBuilder endpoints, String clientAssemblyFilePath, String pattern, String filePath)
   at Microsoft.AspNetCore.Builder.BlazorHostingEndpointRouteBuilderExtensions.MapFallbackToClientSideBlazor[TClientApp](IEndpointRouteBuilder endpoints, String filePath)
   at MLS.Agent.Startup.<>c.<Configure>b__12_3(IEndpointRouteBuilder endpoints) in F:\workspace.13\_work\1\s\MLS.Agent\Startup.cs:line 178
   at Microsoft.AspNetCore.Builder.EndpointRoutingApplicationBuilderExtensions.UseEndpoints(IApplicationBuilder builder, Action`1 configure)
   at MLS.Agent.Startup.<>c.<Configure>b__12_1(IApplicationBuilder blazor) in F:\workspace.13\_work\1\s\MLS.Agent\Startup.cs:line 179
   at Microsoft.AspNetCore.Builder.MapExtensions.Map(IApplicationBuilder app, PathString pathMatch, Action`1 configuration)
   at MLS.Agent.Startup.Configure(IApplicationBuilder app, IHostApplicationLifetime lifetime, IBrowserLauncher browserLauncher, IDirectoryAccessor directoryAccessor, PackageRegistry packageRegistry) in F:\workspace.13\_work\1\s\MLS.Agent\Startup.cs:line 182
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
```

**Comment by rchande** [comment]
@RealTadango In my case, this was happening because we were calling "UseContentRoot" in a way that could cause it to be something other than the location of our assembly. Changing it to:
```csharp
.UseContentRoot(Path.GetDirectoryName(typeof(Program).Assembly.Location))
```

seems to help.

**Comment by RealTadango** [comment]
@rchande I don't use UseContentRoot

**Comment by Rora** [comment]
Any workaround for this? UseContentRoot didn't work for me

**Comment by jsheely** [comment]
Still a problem with preview7

**Comment by danroth27** [comment]
@javiercn Possibly related to #11609?

**Comment by javiercn** [comment]
It is, but blazor has its own mechanism to expose the files to the application host.

**Comment by mkArtakMSFT** [comment]
This will be fixed soon.

**Comment by digitalsigi** [comment]
With 3.0.100-preview9-014004 still the same.
`
System.ArgumentException
  HResult=0x80070057
  Message=The path must be absolute.
  Source=Microsoft.Extensions.FileProviders.Physical
  StackTrace:
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Microsoft.AspNetCore.Builder.BlazorHostingApplicationBuilderExtensions.UseClientSideBlazorFiles(IApplicationBuilder app, String clientAssemblyFilePath)
   at Microsoft.AspNetCore.Builder.BlazorHostingApplicationBuilderExtensions.UseClientSideBlazorFiles[TClientApp](IApplicationBuilder app)
   at BlazorDocker.Server.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in C:\Users\jbogad\source\repos\BlazorDocker\Server\Startup.cs:line 37
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)

`

**Comment by petrformanek** [comment]
I have the same issue with .net core 3 preview 9.
The path is clientAssemblyFilePath == "/app/bin/Debug/netcoreapp3.0/MessagingManagement.UI.dll"
Any ETA when it will be fixed?

System.ArgumentException
  HResult=0x80070057
  Message=The path must be absolute.
  Source=Microsoft.Extensions.FileProviders.Physical
  StackTrace:
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Microsoft.AspNetCore.Builder.BlazorHostingApplicationBuilderExtensions.UseClientSideBlazorFiles(IApplicationBuilder app, String clientAssemblyFilePath)
   at Microsoft.AspNetCore.Builder.BlazorHostingApplicationBuilderExtensions.UseClientSideBlazorFiles[TClientApp](IApplicationBuilder app)
   at MessagingManagement.Server.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in C:\Projects\PoC\MessagingManagementUI\src\MessagingManagement.Server\Startup.cs:line 57

**Comment by javiercn** [comment]
The fix is available in the public preview version of visual studio and will be generally available in the next update.

Closing this as there's no need for further action.

**Comment by Herdo** [comment]
@javiercn @mkArtakMSFT This is marked as closed with **`3.1.0-preview 1`**. However, this error still occurs with an ASP.NET Core hosted WebAssemlby project.

**.NET Core Version:** 3.1.0-preview1.19506.1
**Visual Studio Version:** 16.4.0 Preview 2.0

```System.ArgumentException
  HResult=0x80070057
  Message=The path must be absolute.
  Source=Microsoft.Extensions.FileProviders.Physical
  StackTrace:
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
   at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
   at Microsoft.AspNetCore.Builder.BlazorHostingApplicationBuilderExtensions.UseClientSideBlazorFiles(IApplicationBuilder app, String clientAssemblyFilePath)
   at Microsoft.AspNetCore.Builder.BlazorHostingApplicationBuilderExtensions.UseClientSideBlazorFiles[TClientApp](IApplicationBuilder app)
   at UNITS.Server.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in S:\herdo-opensource\HoU UNITS\src\UNITS\Server\Startup.cs:line 255
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.ApplicationInsights.AspNetCore.ApplicationInsightsStartupFilter.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHost.<StartAsync>d__27.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.<RunAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.<RunAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at UNITS.Server.Program.Main(String[] args) in S:\herdo-opensource\HoU UNITS\src\UNITS\Server\Program.cs:line 16
```

**Comment by javiercn** [comment]
This is related to webassembly, which we will be focusing on in the coming months

**Comment by Herdo** [comment]
@javiercn So should I make a new issue for the [blazor-wasm milestone](https://github.com/aspnet/AspNetCore/milestone/58) - referencing this issue, and/or #10747? I don't seem to find any other issue reporting this problem for that milestone.
